initialiseATP changes
ItzRick/WritingDashboard pull request #101
Opened 2022-06-26 20:36 UTC by tjheij

Changed urls of clickdata in initialiseATP to be realistic
Change participant passwords in initialiseATPNoFiles to 'PartPass1' and add project and participant to it for sidebar test

2022-06-26 20:44 UTC, PFvanBeerendonk requested changes
fix wat rick net zei in Discord

Also, hebben we voor par2 geen pass nodig? (als dat niet zo is, dan is t fine)

2022-06-26 20:54 UTC, tjheij commented
Hij verandert de password voor elke participant in de list participants

2022-06-27 00:05 UTC, marklangedijk reviewed
Ziet er netjes uit;

Miste comments

2022-06-27 00:05 UTC, marklangedijk commented on WriterDesk1/backend/app/loginapi/routes.py
>      try:
Mis comments

2022-06-27 00:05 UTC, marklangedijk commented on WriterDesk1/backend/app/loginapi/routes.py
>      try:
Mis comments

2022-06-27 04:51 UTC, merged