Fix wrong date upload
ItzRick/WritingDashboard pull request #108
Opened 2022-06-27 15:16 UTC by marklangedijk

2022-06-27 17:41 UTC, ItzRick requested changes
Zie comment, voelt nu best random wat je doet...

2022-06-27 17:41 UTC, ItzRick commented on WriterDesk1/src/components/UploadSingleFile.js
> +                            var tempdate = new Date(newDate);
Misschien commentje bijplaatsen wand dit voelt nu best wel random

2022-06-28 14:05 UTC, marklangedijk commented
@ItzRick Ik heb een comment toegevoegd

2022-06-28 19:37 UTC, ItzRick approved these changes
Helemaal top!

2022-06-29 09:33 UTC, merged