removed unused functions from convertPdfToText, added test cases
ItzRick/WritingDashboard pull request #139
Opened 2022-07-01 21:10 UTC by tjheij

Removed functions from convertPdfToText that were never called.
Added test cases for invalid participant password and already existing participant.
The two lines in addParticipantsToExistingProject in projectapi/routes.py can't be tested, the first one because if the current_user is invalid, a 401 is already sent before the check is reached, the second one because it is run after the http response is sent, which doesn't happen with the test client and it's test response objects.

2022-07-02 05:49 UTC, ItzRick requested changes
Zie comments!

2022-07-02 05:49 UTC, ItzRick commented on WriterDesk1/backend/tests/functional/test_generate_participants.py
> +    with pytest.raises(Exception) as e:
zou het netter vinden om dit te importen met from pytest import raises, maar dit kan ook

2022-07-02 05:49 UTC, ItzRick commented on WriterDesk1/backend/tests/functional/test_generate_participants.py
> +            password: string returned by generateParticipantPassword
e moet hier vgm ook bij

2022-07-02 05:49 UTC, ItzRick commented on WriterDesk1/backend/tests/functional/testf_database.py
> +            user: returned user from postParticipant()
e moet hier vgm ook bij...

2022-07-03 16:30 UTC, ItzRick requested changes
Zie comments

2022-07-03 16:30 UTC, ItzRick commented on WriterDesk1/backend/tests/functional/test_pdf_to_text.py
> +            dir_path: path of the directory that holds this file and the test pdf.
zou fileDir moeten zijn vgm, verder mist BASEDIR

2022-07-03 16:30 UTC, ItzRick commented on WriterDesk1/backend/tests/functional/test_pdf_to_text.py
> +            dir_path: path of the directory that holds this file and the test pdf.
zou fileDir moeten zijn, verder mist BASEDIR

2022-07-03 16:34 UTC, tjheij commented
Die os.remove(path) is verwerkt in de test case, die andere is echt niet te testen. De hele check if current user exists zou weg kunnen om de coverage 100% te maken, aangezien hij volgens mij nooit voor kan komen, maar dat zou wel veranderen van de code zijn.

2022-07-03 16:58 UTC, ItzRick approved these changes
helemaal top!

2022-07-03 16:58 UTC, ItzRick commented
> Die os.remove(path) is verwerkt in de test case, die andere is echt niet te testen. De hele check if current user exists zou weg kunnen om de coverage 100% te maken, aangezien hij volgens mij nooit voor kan komen, maar dat zou wel veranderen van de code zijn.

Als het niet kan gebeuren zou ik eerder de code aanpassen (of we moeten gaanuitleggen waarvoor we dat niet reachen), maar snap deze comment niet zo

2022-07-03 18:52 UTC, merged